FROM python:3.11

WORKDIR /app

COPY . .

RUN chmod +x wait-for-it.sh
RUN pip install --no-cache-dir -r requirements.txt

CMD ./wait-for-it.sh mysql:3306 --timeout=60 --strict -- python setup_db.py && python db_seed.py

